spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rule_engine_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework: debug
      drools: DEBUG
      kie: DEBUG
    com:
      example: DEBUG